version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: user-api-db
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=mangovitajuice
      - POSTGRES_PASSWORD=doriga
    ports:
      - "5432:5432"